### ISSUE TITLE
Ozcam AWS show occurrence record error

### ISSUE THREAD

**Issue by patkyn** [AtlasOfLivingAustralia/ozcam-hub#5]
Ozcam hub with biocache-clustered is currently showing an error when displaying duplicate rowkey dataresourceid

https://ozcam-beta.ala.org.au/occurrences/8936b6b5-a527-43e9-96d3-0804cb532727

This is caused by https://github.com/AtlasOfLivingAustralia/biocache-hubs/blob/master/grails-app/views/occurrence/show.gsp#L437 which is trying to get the dr info from rowKey.

This is related to https://github.com/AtlasOfLivingAustralia/biocache-service/issues/254

A temporary fix would be to obtain the dr by querying the biocache with the duplicated record uuid

**Comment by ansell** [comment]
Verified this is fixed
