### ISSUE TITLE
Layout is not being responsive on mobile views

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/ozcam-hub#8]
When the screen width is less than 768 px, the hamburger icon appears but the menu items are still displayed, causing the header to take up 3 rows of text.

![image](https://user-images.githubusercontent.com/532845/92418190-916f9f00-f1a9-11ea-97b2-53d6a5a3482f.png)

The expected behaviour is for the menu items to be hidden and only shown when the user clicks the hamburger icon.

**Comment by nickdos** [comment]
@Rita-C please test issue is fixed on ~https://ozcam.ala.org.au/~ https://ozcam-test.ala.org.au/

**Comment by Rita-C** [comment]
Used chrome Device Toggle Toolbar, hamburger icon appears but the menu items are still displayed, on https://ozcam.ala.org.au/
![Screen Shot 2020-09-11 at 10 08 44 am](https://user-images.githubusercontent.com/29115246/92829030-10b5da80-f417-11ea-9b1d-711984572e0e.png)

**Comment by nickdos** [comment]
Oops should've been on ozcam-test, sorry

**Comment by Rita-C** [comment]
I was wondering about the url :), this is on test - good to go:

![Screen Shot 2020-09-11 at 10 36 22 am](https://user-images.githubusercontent.com/29115246/92832282-c9c9e400-f41a-11ea-83dd-62cf8251360d.png)
